version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache-TP1
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8001:80
